use provided ENV in place of localhost if it exists
chiefbiiko/dynamodb pull request #27
Opened 2020-12-12 03:59 UTC by revgum

It'd be quite handy to have the ability to specify a dynamodb host name in place of localhost, the use-case I have is running a deno app inside of a docker container that needs to connect to a local dynamodb running on the docker host machine.. so in this case I can set DYNAMODB_HOST=host.docker.internal and it'll make the connection properly.

2020-12-14 09:44 UTC, chiefbiiko commented
cool, thanks a lot for bringing up this issue!
instead of using that `DYNAMODB_HOST` env var could you add a `host` prop to `ClientConfig` and then pass it to and use it in `deriveConfig` / `deriveHostEndpoint`
that way, `ClientConfig` surfaced with `createClient` will remain the primary touch point for client configuration

2020-12-14 14:15 UTC, revgum commented
Good call for sure. I reworked the implementation and added coverage.

2020-12-15 12:21 UTC, chiefbiiko requested changes
thanks, will merge after the proposed changes

2020-12-15 12:21 UTC, chiefbiiko commented on client/derive_config.ts
> +  host?: string
can u pls change these to `port = 8000` and `host = "localhost"`
and drop the defaults in the func body

2020-12-15 12:21 UTC, chiefbiiko commented on mod.ts
> +  host?: string; // localhost
pls also adjust the `ClientConfig` interface definition in the [README](https://github.com/chiefbiiko/dynamodb#basics)

2020-12-18 15:46 UTC, chiefbiiko commented
thanks a lot!

2020-12-18 15:48 UTC, merged